name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      chrome:
        image: selenium/standalone-chrome:latest
        options: --shm-size="2g"
        ports:
          - 4444:4444

    env:
      SPRING_SECURITY_USER_NAME: user
      SPRING_SECURITY_USER_PASSWORD: user
      APP_BASE_URL: http://localhost:8080
      SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Start Spring Boot app
        run: |
          JAR_FILE=$(ls target/*.jar | grep -v "original" | head -n 1)
          echo "Starting $JAR_FILE..."
          nohup java -jar $JAR_FILE --spring.profiles.active=test > target/spring.log 2>&1 &

          # Wait for app to start
          echo "Waiting for Spring Boot app..."
          for i in {1..60}; do
            if curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' > /dev/null; then
              echo "App is up!"
              break
            fi
            sleep 2
          done

          if ! curl -s http://localhost:8080/actuator/health | grep '"status":"UP"'; then
            echo "App failed to start"
            cat target/spring.log
            exit 1
          fi

      - name: Run tests
        run: mvn test -Dspring.profiles.active=test \
          -Dselenium.remote=false \
          -Dapp.baseUrl=${APP_BASE_URL}
